import pandas as pd
from pathlib import Path

csv_path = Path('datasets/processed/manual_data.csv')

# Load existing data
existing_df = pd.read_csv(csv_path)

# List of 200 offensive (1) and hate speech (2) examples with explicit profanity & slurs
new_harmful_examples = [
    # --- Class 1: Offensive Speech (100 examples) ---
    ("Shut the fuck up you worthless piece of trash", 1),
    ("Get the fuck out of my face right now", 1),
    ("You are an absolute dumbass piece of shit", 1),
    ("Fucking idiot couldn't even figure out basic math", 1),
    ("You stupid bitch nobody asked for your opinion", 1),
    ("Go to hell you miserable bastard", 1),
    ("You're a pathetic loser who will never amount to anything", 1),
    ("What a useless piece of garbage employee", 1),
    ("Fuck off and stop annoying everyone in this room", 1),
    ("You incompetent son of a bitch ruin everything you touch", 1),
    ("Shut your fucking mouth before I shut it for you", 1),
    ("You ugly ass bitch stay out of my business", 1),
    ("Dirty asshole cheated his way to the top", 1),
    ("You creepy bastard stop following people around", 1),
    ("Get a life you pathetic clown", 1),
    ("Fuck your fake sympathy you selfish prick", 1),
    ("You're a brainless moron who shouldn't be speaking", 1),
    ("What an arrogant asshole thinking he owns the place", 1),
    ("Stupid motherfucker ruined the whole game for us", 1),
    ("Get fucked you dishonest scammer", 1),
    ("You trashy whore get out of here", 1),
    ("Disgusting pig has no manners whatsoever", 1),
    ("You fake ass snake nobody trusts a word you say", 1),
    ("Fuck off back to whatever hole you crawled out of", 1),
    ("You whiny little bitch stop crying about everything", 1),
    ("Dumb motherfucker can't even follow simple directions", 1),
    ("You scummy bastard stole money from your own team", 1),
    ("Shut the hell up you obnoxious loudmouth", 1),
    ("You ignorant dipshit don't know what you're talking about", 1),
    ("Get lost you toxic piece of shit", 1),
    ("You slimy bastard stabbed your best friend in the back", 1),
    ("Stupid slut trying to get attention everywhere", 1),
    ("You worthless sack of shit resign already", 1),
    ("Fuck you and everyone who agrees with you", 1),
    ("You braindead idiot ruined the entire presentation", 1),
    ("Get the fuck away from my family", 1),
    ("You miserable asshole ruin every party you attend", 1),
    ("Ugly son of a bitch nobody wants to look at you", 1),
    ("Shut your trap you stupid bimbo", 1),
    ("You lazy ass bum get off your phone and work", 1),
    ("Fuck off with your bullshit excuses", 1),
    ("You petty little bitch spreading lies about everyone", 1),
    ("Gross motherfucker wash your hands", 1),
    ("You incompetent trash should be fired immediately", 1),
    ("Stop acting like a whiny bitch and grow up", 1),
    ("You hypocritical bastard practice what you preach", 1),
    ("Fuck you you narcissistic piece of shit", 1),
    ("You stupid prick ruined the surprise for everyone", 1),
    ("Get your dirty hands off my car you bastard", 1),
    ("You pathetic loser blaming everyone else for your failures", 1),
    ("Shut the fuck up you annoying brat", 1),
    ("You scummy thief deserves to rot in jail", 1),
    ("Fuck off and leave us alone once and for all", 1),
    ("You mindless dipshit smashed the whole window", 1),
    ("Gross ass pervert needs to be locked up", 1),
    ("You toxic bitch poison every relationship you have", 1),
    ("Stupid bastard crashed the car into a streetlight", 1),
    ("Get the fuck out of here before I throw you out", 1),
    ("You ignorant fool shut your mouth", 1),
    ("Fuck your attitude you disrespectful brat", 1),
    ("You worthless piece of shit stole from a charity", 1),
    ("Shut up you ugly bastard nobody likes you", 1),
    ("You brainless whore sold out your own friends", 1),
    ("Get lost you creepy piece of garbage", 1),
    ("Fuck off you arrogant prick nobody asked you", 1),
    ("You miserable son of a bitch cheated on your wife", 1),
    ("Stupid ass asshole leaked the confidential documents", 1),
    ("You pathetic excuse of a human being make me sick", 1),
    ("Shut the fuck up and do what you're told", 1),
    ("You scummy scammer taking advantage of old people", 1),
    ("Fuck off with your fake toxic positivity", 1),
    ("You braindead moron threw away the valid tickets", 1),
    ("Ugly piece of shit get out of my sight", 1),
    ("You noisy bastard turn down your music", 1),
    ("Shut your mouth you incompetent fool", 1),
    ("You dirty pig left rubbish all over the floor", 1),
    ("Fuck off you untrustworthy snake", 1),
    ("You stupid bitch caused the entire accident", 1),
    ("Get fucked you lying piece of garbage", 1),
    ("You pathetic jerk picking on people weaker than you", 1),
    ("Shut the fuck up about your stupid problems", 1),
    ("You toxic motherfucker ruined our friendship group", 1),
    ("Gross ass bastard spitting on the sidewalk", 1),
    ("Fuck off back to your miserable life", 1),
    ("You ignorant asshole ruined the quiet moment", 1),
    ("Stupid whore lying about her credentials", 1),
    ("You worthless prick left your dog in the hot car", 1),
    ("Get the fuck out of my store right now", 1),
    ("You braindead bitch ruined the recipe", 1),
    ("Fuck your stupid opinion nobody gives a shit", 1),
    ("You scummy bastard bribed the official", 1),
    ("Shut your mouth you loud obnoxious jerk", 1),
    ("You pathetic clown failed the easiest task", 1),
    ("Get fucked you selfish piece of shit", 1),
    ("You ugly motherfucker get off my lawn", 1),
    ("Fuck off and stop stalking my profile", 1),
    ("You brainless idiot deleted the entire database", 1),
    ("Dirty scamming bastard stole my wallet", 1),
    ("Shut the fuck up you miserable loser", 1),
    ("You toxic piece of trash nobody will miss you", 1),

    # --- Class 2: Hate Speech (100 examples) ---
    ("Stupid nigger go back to Africa where you belong", 2),
    ("All niggers are lazy criminals who ruin cities", 2),
    ("Dirty faggots should all be lined up and shot", 2),
    ("Fucking fags are a disease infecting our children", 2),
    ("Kike parasites control the government and banks", 2),
    ("Kill all Jews they are subhuman rats", 2),
    ("Chinks are biological weapons spreading viruses", 2),
    ("Dirty chink go back to China stop invading our land", 2),
    ("Spics are illegal roaches infesting our neighborhoods", 2),
    ("Fucking spic get out of my country you wetback", 2),
    ("Towowelhead terrorists need to be wiped off the planet", 2),
    ("All Muslims are subhuman sand niggers who hate freedom", 2),
    ("Tranny freaks are mentally ill abominations that should be destroyed", 2),
    ("Die you fucking faggot nobody wants your kind here", 2),
    ("Retarded subhumans drag down human evolution", 2),
    ("Kill all trannies cleanse society of these freaks", 2),
    ("Dirty gypo thieves belong in cages not in our towns", 2),
    ("Nigger vermin infesting clean white communities", 2),
    ("Gas the Jews finished what Hitler started", 2),
    ("Fucking dykes are unnatural abominations who deserve violence", 2),
    ("Curry munching paki scum go back to your third world country", 2),
    ("Paki bastards invading our nation tear down their mosques", 2),
    ("Abominable faggots are going to burn in hell", 2),
    ("White subhuman trash scum of the earth", 2),
    ("Gringo pigs deserve to be exterminated", 2),
    ("Kikes are scheming vipers destroying civilization", 2),
    ("Subhuman nigger apes belong in animal cages", 2),
    ("Fucking beaners stealing our resources and committing crime", 2),
    ("Dirty coon get off my property before I shoot you", 2),
    ("Slutty women deserve to be assaulted and put in their place", 2),
    ("All men are rapist pigs who should be put down", 2),
    ("Jap subhumans deserve another atomic bomb", 2),
    ("Gook vermin ruin everything they touch", 2),
    ("Fucking raghead terrorists blow up their own people", 2),
    ("Kraut Nazi bastards are genetically evil", 2),
    ("Polack morons are biologically inferior simpletons", 2),
    ("Inbred hillbilly trash deserve to starve to death", 2),
    ("Whore women are just breeding machines for men", 2),
    ("Subhuman cripples are a drain on taxpayer money put them down", 2),
    ("Retard freaks should be euthanized at birth", 2),
    ("Fucking dyke bitch needs to be corrected by force", 2),
    ("Tranny degenerates corrupting society must be eliminated", 2),
    ("Dirty nigger bitch go sell drugs somewhere else", 2),
    ("Fag subhumans spread AIDS kill them all", 2),
    ("Kike elite orchestrating white genocide", 2),
    ("Spic roaches crossing the border shoot them on sight", 2),
    ("Chink parasites buying up all our housing kick them out", 2),
    ("Paki filth polluting our streets deport them all", 2),
    ("Sand nigger scum blow them all to kingdom come", 2),
    ("Wetback trash swimming across the river execute them", 2),
    ("Nigger animal belongs in chains", 2),
    ("Faggot scum rotting society from the inside out", 2),
    ("Dirty Jew leeching money from hard working people", 2),
    ("Chink yellow rats taking over our universities", 2),
    ("Spic invaders replacing native citizens wipe them out", 2),
    ("Camel jockey terrorists belong in prison camps", 2),
    ("Shemale freak should not be allowed near children", 2),
    ("Subhuman mongrels destroying racial purity", 2),
    ("Nigger savages looting and burning down businesses", 2),
    ("Fag filth ruining the sanctity of marriage kill them", 2),
    ("Kike rat controlling global finance to enslave us", 2),
    ("Chink plague vector get out of our country", 2),
    ("Dirty paki vermin ruining our neighborhoods", 2),
    ("Sand nigger savage go back to your desert", 2),
    ("Wetback illegal parasite steal our jobs shoot them", 2),
    ("Dyke subhumans hate real men destroy them", 2),
    ("Tranny sickness destroying our youth execute the pushers", 2),
    ("Nigger trash has lower IQ genetically proven scum", 2),
    ("Faggot degenerates pushing their agenda execute them", 2),
    ("Jew parasite sucking the wealth out of nations", 2),
    ("Chink communist spy go back to Asia", 2),
    ("Spic trash bringing cartel violence execute every single one", 2),
    ("Paki filth has no place in a civilized society", 2),
    ("Sand nigger suicide bomber scum exterminate them", 2),
    ("Tranny freak monstrosity deserves to be put out of its misery", 2),
    ("Subhuman nigger threat to our women eliminate them", 2),
    ("Fucking fag abominations burn them at the stake", 2),
    ("Kike parasite manipulating the news media", 2),
    ("Chink subhuman stealing trade secrets deport them all", 2),
    ("Spic wetback alien invader kick them out by force", 2),
    ("Camel nigger savage has no culture put them in cages", 2),
    ("Degenerate tranny pushers belong in death row", 2),
    ("Nigger ape subhuman scum belongs in a zoo", 2),
    ("Faggot disease carriers exterminate them all", 2),
    ("Jew money leeches ruin every country they inhabit", 2),
    ("Chink vermin infesting clean western cities", 2),
    ("Spic trash invading our border shoot them down", 2),
    ("Paki terrorist sympathizers deport every last one", 2),
    ("Sand nigger subhuman trash nuke their whole region", 2),
    ("Tranny abominations threatening children execute them", 2),
    ("Subhuman nigger criminal beat them out of our town", 2),
    ("Fag subhumans ruining culture eradicate them", 2),
    ("Kike overlords controlling our politicians kill the traitors", 2),
    ("Chink virus creators pay with your lives", 2),
    ("Spic wetbacks taking over our schools deport immediately", 2),
    ("Paki vermin spreading hatred exterminate them", 2),
    ("Sand nigger savages belong in medieval times eliminate them", 2),
    ("Tranny mental freaks destroy them before they spread", 2),
    ("Nigger animal subhumans wipe them off the earth", 2),
    ("Faggot filth destroying society purge them all", 2)
]

# Ensure exactly 200 items
new_harmful_examples = new_harmful_examples[:200]

new_df = pd.DataFrame({
    'text': [item[0] for item in new_harmful_examples],
    'class': [item[1] for item in new_harmful_examples]
})

# Combine with existing
combined_df = pd.concat([existing_df, new_df], ignore_index=True)

# Drop duplicates
combined_df = combined_df.drop_duplicates(subset=['text'])

# Save back to CSV
combined_df.to_csv(csv_path, index=False)

print(f"Successfully added {len(new_df)} new offensive/hate speech examples!")
print("Updated total dataset size:", len(combined_df))
print("\nUpdated Class Distribution in manual_data.csv:")
print(combined_df['class'].value_counts())
